
###
GET http://localhost:8080/recipe/0

###
POST http://localhost:8080/recipe
content-type: application/json

{
  "0": {
    "title": "Recipe 1",
    "cookingTime": 30,
    "Ingredients": [
      {"title": 1,
        "quantity": 1,
        "measuringUnit": "kg"
      }
    ],
    "steps": [
      "Step 1",
      "Step 2"
    ]
  }
}

###
POST http://localhost:8080/recipe/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="recipes"; filename="importRecipes.json"
Content-Type: application/json

< ./importRecipes.json
--WebAppBoundary--

###
POST http://localhost:8080/ingredient/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="ingredients"; filename="importIngredients.json"
Content-Type: application/json

< ./importIngredients.json
--WebAppBoundary--