
###
GET http://localhost:8080/recipe/0

###
POST http://localhost:8080/recipe
content-type: application/json

{
  "id": 1,
  "title": "Recipe 1",
  "cookingTime": 30,
  "Ingredients": [
    {
      "title": 1,
      "quantity": 1,
      "measuringUnit": "kg"
    },
    {
      "title": 1,
      "quantity": 1,
      "measuringUnit": "kg"
    },
    {
      "title": 1,
      "quantity": 1,
      "measuringUnit": "kg"
    }
  ],
  "steps": [
    "Step 1",
    "Step 2"
  ]
}